# Generated by Django 3.1.5 on 2021-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='StudentUser name')),
                ('email', models.CharField(max_length=50, verbose_name='StudentUser email')),
                ('password', models.CharField(max_length=20, verbose_name='StudentUser Password')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='TeacherUser name')),
                ('email', models.CharField(max_length=50, verbose_name='TeacherUser email')),
                ('password', models.CharField(max_length=20, verbose_name='TeacherUser Password')),
            ],
        ),
    ]
