# Generated by Django 3.1.5 on 2021-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degreestudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField(max_length=20)),
                ('mobile', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField(max_length=20)),
                ('mobile', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Twelvestudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('marks', models.IntegerField(max_length=20)),
                ('mobile', models.IntegerField(max_length=20)),
            ],
        ),
    ]
