# Generated by Django 3.1.5 on 2021-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_degreestudent_tenstudent_twelvestudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='marks',
            new_name='css',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='mobile',
            new_name='html',
        ),
        migrations.RenameField(
            model_name='tenstudent',
            old_name='marks',
            new_name='hindi',
        ),
        migrations.RenameField(
            model_name='tenstudent',
            old_name='mobile',
            new_name='marathi',
        ),
        migrations.RenameField(
            model_name='twelvestudent',
            old_name='marks',
            new_name='chemistry',
        ),
        migrations.RenameField(
            model_name='twelvestudent',
            old_name='mobile',
            new_name='computer',
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='javscript',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='python',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='maths',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='science',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='maths',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='physics',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
