# Generated by Django 3.1.5 on 2021-04-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0006_auto_20210422_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degreestudent',
            old_name='css',
            new_name='sem1',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='javscript',
            new_name='sem2',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='html',
            new_name='sem3',
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='sem4',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='sem5',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='sem6',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='sem7',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='sem8',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='tenth',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreestudent',
            name='twelth',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='english',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='history',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='sport',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='english',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='hindi',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='sport',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='tenth',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degreestudent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.studentuser'),
        ),
        migrations.AlterField(
            model_name='tenstudent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.studentuser'),
        ),
        migrations.AlterField(
            model_name='twelvestudent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.studentuser'),
        ),
    ]
