# Generated by Django 3.1.5 on 2021-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_auto_20210422_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degreestudent',
            old_name='python',
            new_name='degree_percentage',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='sem1',
            new_name='first_year',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='sem2',
            new_name='second_year',
        ),
        migrations.RenameField(
            model_name='degreestudent',
            old_name='sem3',
            new_name='third_year',
        ),
        migrations.RemoveField(
            model_name='degreestudent',
            name='sem4',
        ),
        migrations.RemoveField(
            model_name='degreestudent',
            name='sem5',
        ),
        migrations.RemoveField(
            model_name='degreestudent',
            name='sem6',
        ),
        migrations.RemoveField(
            model_name='degreestudent',
            name='sem7',
        ),
        migrations.RemoveField(
            model_name='degreestudent',
            name='sem8',
        ),
        migrations.AddField(
            model_name='tenstudent',
            name='total',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelvestudent',
            name='total',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
